# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:56
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, default='', upload_to=blog.models.set_image_name),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='', upload_to=blog.models.set_image_name, verbose_name='Главное изображение'),
        ),
    ]
