# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='product',
        ),
    ]
