# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import information.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_remove_condition_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=information.models.set_file_name, verbose_name='Файл')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
