# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:56
from __future__ import unicode_literals

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170727_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=catalog.models.set_image_name),
        ),
        migrations.AlterField(
            model_name='catalogimage',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=catalog.models.set_image_name, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=catalog.models.set_image_name, verbose_name='Изображение'),
        ),
    ]
