# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_providerfile'),
        ('catalog', '0005_catalogproduct_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='provider_price',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='information.ProviderFile', verbose_name='Прайс поставщика'),
        ),
    ]
